-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 22:59:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema text
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema text
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `text` DEFAULT CHARACTER SET utf8 ;
USE `text` ;

-- -----------------------------------------------------
-- Table `text`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `text`.`text` (
  `id_texts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_texts`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
